# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: vendor

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/golangci/golangci-lint
  rev: v1.57.2
  hooks:
  - id: golangci-lint
    entry: golangci-lint run --fix
    require_serial: true
    verbose: true

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    require_serial: true
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    require_serial: true
    args: [--autofix]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.2
  hooks:
  - id: gitleaks

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.1-beta
  hooks:
  - id: hadolint-docker

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.1
  hooks:
  - id: check-github-workflows
