definitions:
  Episode:
    properties:
      file:
        type: string
      name:
        type: string
    type: object
  Health:
    properties:
      apiVersion:
        description: Version - public version of the service. (API version).
        example: "1"
        type: string
      description:
        description: Description - a human-friendly description of the service.
        type: string
      notes:
        description: Notes - array of notes relevant to current state of health.
        example:
        - 'commit hash: aee0773'
        - 'uptime: 12.3s'
        items:
          type: string
        type: array
      revision:
        type: string
      status:
        allOf:
        - $ref: '#/definitions/HealthStatus'
        description: |-
          Status indicates whether the service status is acceptable or not.
          - `pass`: healthy (acceptable aliases: "ok" to support Node's Terminus and "up" for Java's SpringBoot),
          - `fail`: unhealthy (acceptable aliases: "error" to support Node's Terminus and "down" for Java's SpringBoot), and
          - `warn`: healthy, with some concerns.
        example: pass
    type: object
  HealthStatus:
    enum:
    - pass
    - fail
    - warn
    type: string
    x-enum-varnames:
    - Pass
    - Fail
    - Warn
  Index:
    properties:
      episodes:
        items:
          $ref: '#/definitions/Episode'
        type: array
    type: object
info:
  contact: {}
  description: stream-recorder is a tool to record live streams.
  title: stream-recorder
paths:
  /health:
    get:
      description: Provides information about the application health.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Health'
      summary: Health Check
      tags:
      - System
  /records:
    get:
      description: Provides list of recorded episodes.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Index'
      summary: Records list
swagger: "2.0"
